### ISSUE TITLE
Segmentation fault issue when testing on a PDF file

### ISSUE THREAD

**Issue by sunnydaychen** [allenai/pdffigures#7]
Tested the program on a pdf file such as http://aclweb.org/anthology/N/N15/N15-3005.pdf, the output is shown as follows:
++++++++++++++++++++++++
Scanned 5 pages

Analyzing Document...
Margin:
        (435.00,102)-(750.00,145)
        (100.00,100)-(415.00,106)
Two Column (0.01)
Right Aligned
Analysis Complete.

Scanning for captions...
Collected 15 candidates for 7 detected captions
Applied filter Colon Only (8 remain)
Applied filter Block Start Only (7 remain)
1 candidates for Figure5, excluding them
1 candidates for Table2, excluding them
1 candidates for Figure3, excluding them
1 candidates for Figure1, excluding them
1 candidates for Figure4, excluding them
1 candidates for Table1, excluding them
1 candidates for Figure2, excluding them
Done parsing captions.

Page 1: Figure1 Table1 Figure2
Page 2: Table2 Figure3
Page 3: Figure5 Figure4
Working on page 1
Segmentation fault
+++++++++++++++++++++++
Looks like the program fails when calling the 3rd party tool "leptonica", did someone come across the same issue? For some other pdf files, sometimes it shows "Error in pixConvertTo1: pixs not defined" then again "Segmentation fault".

**Comment by chrisc36** [comment]
I fixed a logging bug, but I was not able to reproduce either the segmentation fault or the warning. Could there be a dependency version issue? I am using leptonica 1.72 and poppler 0.29.
If that is not it, do you have any other examples when this occurs?

**Comment by sunnydaychen** [comment]
Yes, the program works fine in Ubuntu, I tested in RedHat before, so there might be some compatible issues for the third party tool poppler.
